version: '3.0'

networks:
  modric:
    driver: bridge

services:
  zookeeper:
    image: 'zookeeper'
    hostname: zoo
    ports:
      - 2181:2181
    networks:
      - modric
    
  kafka:
    depends_on:
      - zookeeper
    image: 'ubuntu/kafka'
    hostname: kafka
    networks:
      - modric
    environment:
      - ZOOKEEPER_HOST=zoo
      - ZOOKEEPER_PORT=2181
    ports:
      - 9092:9092

  producer:
    image: producer
    build:
      dockerfile: ./producer.Dockerfile
      context: ./producer/
    ports:
      - 8080:8080
    networks:
      - modric
    environment:
      - BROKER=kafka:9092
    depends_on:
      - kafka

  consumer:
    image: consumer
    build:
      dockerfile: ./consumer.Dockerfile
      context: ./consumer/
    ports:
      - 8081:8081
    environment:
      - BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - modric